### ISSUE TITLE
Checkstyle 0 warnings

### ISSUE THREAD

**Issue by costris95** [AlejandroPeralTaboada/VVS#13]
Solucionados todos los warnings de checkstyle

**Comment by lauramcastro** [comment]
Esto no debería ser una nueva _issue_, sino el mensaje de cierre de la _issue_ #12 :)

**Comment by lauramcastro** [comment]
No olvidéis clasificar cada _issue_ con etiquetas y responsables en la columna de la derecha en GitHub.
