### ISSUE TITLE
Build de Travis-CI falla pero no por pruebas que no pasen

### ISSUE THREAD

**Issue by lauramcastro** [AlejandroPeralTaboada/VVS#14]
A partir de ahora, el único motivo aceptable para que las build de Travis fallen debería ser que estén fallando casos de prueba (es decir, que haya bugs detectados aún no resueltos). Vuestro repositorio ahora mismo non se construye porque falla la compilación de las pruebas. Procurad que esto no ocurra.

**Comment by costris95** [comment]
Corregido, un problema de float vs Float
