### ISSUE TITLE
Aserción de excepciones

### ISSUE THREAD

**Issue by lauramcastro** [AlejandroPeralTaboada/VVS#15]
La [manera adecuada de asegurarse en un caso de prueba de que se lanza una excepción](https://github.com/junit-team/junit4/wiki/Exception-testing) (prueba negativa) es usar el `assert` en la parte del `catch` de la estructura `try-catch` que habéis empleado, o alternativamente usar el _tag_ `@Test(expected = ExcepcionConcreta.class)`. Modificad las pruebas para corregirlo.

**Comment by costris95** [comment]
Corregido, elegida la segunda opción con el tag @Test(expected = IllegalArgumentException.class)
Gracias Laura.
